### ISSUE TITLE
Failed to compile firmware

### ISSUE THREAD

**Issue by NeonSweet** [csurf/mstar#1]
Hello, I'm an FPV player. My English is not very good, I use a translation software to ask you questions.

I want to assemble a monitor for FPV flight. I bought a LCD driver board with mst703 as the main control chip and a 5-inch LCD screen with 800 * 480 resolution, but the firmware of this driver board only supports 480 * 272 resolution. I searched the Internet for ways to modify the firmware and finally found your project. I successfully compiled the project of "BG_zcd706_5in" in Windows 10, and got the binary file with suffix. H00. H01. How can I merge. H00 and. H01 files into. Bin firmware? I try to change the board type to "DX"_ 703_ 5in ", but the compilation failed. This is a screenshot of an error in keil.The memory used on the board is w25q40bv. How can I modify the memory type? 
![image](https://user-images.githubusercontent.com/26185476/120888683-3d0c2980-c62c-11eb-9905-4ed71777d724.png)

I see that you are using keil to compile the firmware under Linux. What is your specific environment? Can you release the compiled firmware? I want to test it.

Best wishes!

**Comment by csurf** [comment]
Ok, I will try to help you in steps, because I have been working on other things, and will need to refresh my memory.
Here is what I can help with right now:
- I am using keil running under wine in fedora linux environment. You will have to play with your wine / keil configuration in order to get this to work, but it shouldn't be too difficult.
- there is a utility included in the repo called 'hex2bin.sh', within the 'project' folder that will merge hex files into a single bin file. Take a look at it. It basically merges the two hex files, using an offset for the second file. The original SDK source code also contains an exe that does the same thing 'hex2bin.exe', but I removed it from my repo in preference of a more standard linux-based solution
-  My memory is foggy, but those errors relate to the defines in your board.h file. You need to disable whichever defines try to enable those features. Look at my working board.h file / configuration, and look for the #define's that relate to those identifiers

when I get time, I will look at the source code again, and help you further, but please try to use those suggestions first, and let me know how it goes.

**Comment by csurf** [comment]
@YQSX did you ever solve this problem? let me know, or I will close this issue

**Comment by NeonSweet** [comment]
Yes, I solved this problem, thank you.
